logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.security: INFO
    com.grupo8.ggbackend: DEBUG
    org.apache.hc.client5.http: INFO

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
